### ISSUE TITLE
Add ability to delete/add SLs and Auditionees

### ISSUE THREAD

**Issue by VinMags16** [VinMags16/audition-web-form#30]
Right now the lists are hard coded.  We need a way to dynamically add SLs and auditionees as well as remove.  Maybe only implement a remove all for removing people.  We should be storing the lists in Firebase and the ability to import students should be able to take in whatever Charms outputs for exporting students.

**Comment by cmilhaupt** [comment]
Not sure what progress has been made on this, but I'd look into using wget to pull a list of students from charms. Doing a quick network check I can see a POST request being sent, so if use wget and pass a username, password, and the post request, we should be able to get a webpage back and parse the names out of it and load that into firebase.

**Comment by VinMags16** [comment]
Not a necessary function of the app right now
