### ISSUE TITLE
Find way to visualize database information

### ISSUE THREAD

**Issue by cmilhaupt** [VinMags16/audition-web-form#7]
I'm imagining a script that'll generate a handful of graphs which allow us to summarize the information from that day/week

- Bar graph that shows total better/worse comments for that day
- Pie chart(?) that shows which criteria was commented on the most
- Statistic that shows ratio of submissions made over total auditionees
- Statistic that shows average comments per person
- Statistic that shows average submissions per student leader

**Comment by VinMags16** [comment]
I know we had ideas on using different JS frameworks but we now need to look into ways to work with Firebase.

**Comment by cmilhaupt** [comment]
I think d3.js is out best bet right now. 
https://d3js.org/

**Comment by VinMags16** [comment]
Plot.ly is looking like the best option now.  It's built on top of D3 and it looks C L E A N.  Plus there's a guide on setting it up
https://www.youtube.com/watch?v=Ga0vrqed6Ho

**Comment by cmilhaupt** [comment]
I really like plot.ly, but their free option only supports 25 charts so I'm not sure if that can scale enough for the trumpet section let alone the whole band.

**Comment by VinMags16** [comment]
Table suffices for now.
